---
title: "Scale Descriptions"
format: html
bibliography: /Users/joseph/GIT/templates/bib/references.bib
csl: apa.csl
---

#### Mini-IPIP 6

We measured participants personality with the Mini International Personality Item Pool 6 (Mini-IPIP6) [@sibley2011] which consists of six dimensions and each dimensions is measured with four items:

1.  agreeableness,

    i.  I sympathize with others' feelings.

    ii. I am not interested in other people's problems. (r)

    iii. I feel others' emotions.

    iv. I am not really interested in others. (r)

2.  conscientiousness,

    i.  I get chores done right away.

    ii. I like order.

    iii. I make a mess of things. (r)

    iv. I ften forget to put things back in their proper place. (r)

3.  extraversion,

    i.  I am the life of the party.

    ii. I don't talk a lot. (r)

    iii. I keep in the background. (r)

    iv. I talk to a lot of different people at parties.

4.  honesty-humility,

    i.  I feel entitled to more of everything. (r)

    ii. I deserve more things in life. (r)

    iii. I would like to be seen driving around in a very expensive car. (r)

    iv. I would get a lot of pleasure from owning expensive luxury goods. (r)

5.  neuroticism, and

    i.  I have frequent mood swings.

    ii. I am relaxed most of the time. (r)

    iii. I get upset easily.

    iv. I seldom feel blue. (r)

6.  openness to experience

    i.  I have a vivid imagination.

    ii. I have difficulty understanding abstract ideas. (r)

    iii. I do not have a good imagination. (r)

    iv. I am not interested in abstract ideas. (r)

Each dimension was assessed with four items and participants rated the accuracy of each item as it applies to them from 1 (Very Inaccurate) to 7 (Very Accurate). Items marked with (r) are reverse coded.


#### Age (waves: 1-15)

We asked participants' ages in an open-ended question ("What is your age?" or "What is your date of birth?").


#### Alcohol Frequency

We measured participants' frequency of drinking alcohol using one item adapted from @Ministry_of_Health_2013. Participants were asked "How often do you have a drink containing alcohol?" (1 = Never - I don't drink, 2 = Monthly or less, 3 = Up to 4 times a month, 4 = Up to 3 times a week, 5 = 4 or more times a week, 6 = Don't know).

#### Alcohol Intensity

We measured participants' intensity of drinking alcohol using one item adapted from @Ministry_of_Health_2013. Participants were asked "How many drinks containing alcohol do you have on a typical day when drinking alcohol? (number of drinks on a typical day when drinking)"

#### Body Mass Index

We asked participants "What is your height? (metres)" and "What is your weight? (kg)". Based on participants indication of their height and weight we calculated the BMI by dividing the weight in kilograms by the square of the height in meters.



#### Body Satisfaction (1 = Very inaccurate to 7 = Very accurate)


* "I am satisfied with the appearance, size and shape of my body"

From @stronge2015facebook


#### Charitable Donations

Using one item from @hoverd_religious_2010, we asked participants "How much money have you donated to charity in the last year?". 

<!-- To stablise this indicator, we took the natural log of the response + 1. -->


#### Charitable Volunteering


We measured hours of volunterering using one item from @sibley2011: "Hours spent … voluntary/charitable work."

<!-- To stablise this indicator, we took the natural log of the response + 1. -->


#### Children Number

We measured number of children using one item from @Bulbulia_2015. We asked participants "How many children have you given birth to, fathered, or adopted. How many children have you given birth to, fathered, or adopted?


#### Community: Sense of Community

We measured sense of community with a single item from @sengupta2013: "I feel a sense of community with others in my local neighbourhood." Participants answered on a scale of 1 (strongly disagree) to 7 (strongly agree).



#### COVID-19 Alert Level

Wave 11 and part of Wave 12 occuried during a global pandemic (SARS-CoV 10), during which New Zealand experienced a series of stringent pandemic lockdowns, which varied by region. We combined regional information with the COVID-19 lockdown timeline to create a multi-level indicator for lockdown-serverity. The levels of this variable are: "no_alert", "early_covid_no_alert",  "alert_level_1",  "alert_level_2", "alert_level_2_5",  "alert_level_3", "alert_level_4".

#### Disability

We assessed disability with a one item indicator adapted from @verbrugge1997, that asks "Do you have a health condition or disability that limits you, and that has lasted for 6+ months?" (1 = Yes, 0 = No).


#### Education

Participants were asked "What is your highest level of qualification?". We coded participans highest finished degree according to the New Zealand Qualifications Authority.



#### Emotional Regulation

We measured participants' levels of emotional regulation using three items adapted from @gratz_multidimensional_2004 and @gross_individual_2003: 

(1) "When I feel negative emotions, my emotions feel out of control.";
(2) "When I feel negative emotions, I suppress or hide my emotions."; 
(3) "When I feel negative emotions, I change the way I think to help me stay calm."


#### Employment

We asked participants "Are you currently employed? (This includes self-employed or casual work)".


#### Ethnicity

Based on the New Zealand Cencus, we asked participants "Which ethnic group(s) do you belong to?". The responses were: (1) New Zealand European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6) Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE, TOKELAUAN. Please state:. We coded their answers into four groups: Maori, Pacific, Asian, and Euro (except for Time 3, which used an open-ended measure).



#### Ethnic group impermeability

We assessed ethnic group impermeability using one item from @mummendey_social_1999. Participants were asked to indicate the extent to which they agree with the statement ("The current income gap between New Zealand Europeans and other ethnic groups would be very hard to change."; 1 = Strongly Disagree to Strongly Agree).

<!-- #### European -->

<!-- Participants were asekd "Which ethnic group do you belong to (NZ census question)?". Europeans were coded as 1, wherease other ethniciities were coded as 0. -->

#### Fatigue (ordinal)

* "During the last 30 days, how often did ... you feel exhausted?" 

Ordinal responses: 0 = None of The Time, 1 = A little of The Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time.


From @sibley2020effects



#### Forgiveness

We assessed participants' forgiveness using reversed scores of a the NZAVS "vengeful rumination scale." This scale contains three items, adapted from @caprara_indicators_1986 and @berry_forgivingness_2005, and developed for NZAVS: 

(1) Sometimes I can't sleep because of thinking about past wrongs I have suffered; 
(2) I can usually forgive and forget when someone does me wrong (reversed scored); 
(3) I find myself regularly thinking about past times that I have been wronged. 

Participants indicated their agreement with these items (1 = Strongly Disagree to 7 = Strongly Agree). 



#### Gender

We asked participants' gender in an open-ended question ("what is your gender?". Female was coded as 0, Male was coded as 1, and gender diverse coded as 3 [@fraser_coding_2020].

#### Gratitude  (1 = Strongly Disagree to 7 = Strongly Agree).

We assessed the extent to which participants have gratitude, using three items from @mccullough_grateful_2002: 

(1) "I have much in my life to be thankful for."; 
(2) "When I look at the world, I don't see much to be grateful for."; (reversed)
(3) "I am grateful to a wide variety of people."

#### Has Siblings

"Do you have siblings?" [@stronge2019onlychild].

#### Home Owner

Using one item from @houkamau_looking_2015, we asked participants "Do you own your own home?(either partly or fully owned)" (1 = Yes, 0 = No)

#### Hours of Childcare

We measured hours of childcare using one item from @sibley2011: 'Hours spent … looking after children."

<!-- To stablise this indicator, we took the natural log of the response + 1. -->

#### Hours of Housework

We measured hours of housework using one item from @sibley2011: "Hours spent … housework/cooking"

<!-- To stablise this indicator, we took the natural log of the response + 1. -->

#### Hours of Exercise

We measured hours of exercise using one item from @sibley2011: "Hours spent … exercising/physical activity" 

<!-- To stablise this indicator, we took the natural log of the response + 1. -->

#### Hours of Work

We measured hours of work using one item from @sibley2011:"Hours spent … working in paid employment."

<!-- To stablise this indicator, we took the natural log of the response + 1. -->

#### Hours of Sleep

"During the past month, on average, how many hours of *actual sleep* did you get per night".

#### Income

Participants were asked "Please estimate your total household income (before tax) for the year XXXX". To stablise this indicator, we first took the natural log of the response + 1, and then centred and standardised the log-transformed indicator.

#### Job Security

Participants indicated their feeling of job security by answering "How secure do you feel in your current job?" on a scale from 1 (not secure) to 7 (very secure).


#### Kessler 6 Anxiety and Kessler 6 Depression (ordinal) (waves: 2-3,4-15)

We measured psychological distress using the Kessler-6 scale (kessler2002?), which exhibits
strong diagnostic concordance for moderate and severe psychological distress in large, crosscultural samples [@kessler2002; @kessler2010?; @prochaska2012]. 


Participants rated during the past 30 days, how often did...

(1) "... you feel hopeless"; 
(2) "...you feel so depressed that nothing could cheer you up"; 
(3) "...you feel restless or fidgety"; 
(4)"...you feel that everything was an effort"; 
(5) "... you feel worthless"; 
(6) "...you feel nervous?"

Ordinal responses: 0 = None of The Time, 1 = A little of The Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time.

A two-factor model fits this scale. We describe the decomposition as: 

**Kesser-6-latent-anxiety**:  "… you feel restless or fidgety”; ” you feel nervous?” “… you feel that everything was
an effort."

**Kesser-6-latent-anxiety**:  “… you feel hopeless”; “… you feel so depressed that nothing
could cheer you up”; “… you feel worthless.”

A two-factor model fits this scale. We describe the decomposition as: 

**Kesser-6-latent-anxiety**:  "… you feel restless or fidgety”; ” you feel nervous?” “… you feel that everything was
an effort."

**Kesser-6-latent-anxiety**:  “… you feel hopeless”; “… you feel so depressed that nothing
could cheer you up”; “… you feel worthless.”



#### Opt-in

The New Zealand Attitudes and Values Study allows opt-ins to the study. Because the opt-in population may differ from those sampled randomly from the New Zealand electoral role; although the opt-in rate is low, we include an indicator (yes/no) for this variable.


#### Political Orientation: Politically Conservative 

We measured participants' political conservative orientation using a single item adapted from @jost_end_2006-1.

"Please rate how politically liberal versus conservative you see yourself as being."

(1 = Extremely Liberal to 7 = Extremely Conservative)


#### Political Orientation: Politically Right Wing 

We measured participants' political right-wing orientation using a single item adapted from @jost_end_2006-1.

"Please rate how politically left-wing versus right-wing you see yourself as being.."

(1 = Extremely left-wing to 7 = Extremely right-wing)


#### Life Meaning (1 = Strongly Disagree to 7 = Strongly Agree)

(1) "My life has a clear sense of purpose;"
(2) "I have a good sense of what makes my life meaningful." 

From @steger_meaning_2006

We assessed these dimensions separately.


#### Life Satisfaction (1 = Strongly Disagree to 7 = Strongly Agree)

1. "I am satisfied with my life"  
2. "In most ways my life is close to ideal". 

From the Satisfaction with Life Scale @diener1985a.


#### Lost Job

Participants were asked to indicate whether they lost their job or had the principal earner in their household lose job in the last year (1 = Yes, 0 = No).


#### National Well-being Index

We measured participant's sense of national well-being by asking them to "Please rate your level of satisfaction with the following aspects of your life and New Zealand: (1) The economic situation in New Zealand, (2) The social conditions in New Zealand, and (3) Business in New Zealand" on a scale from 0 (Completely Dissatisfied) to 10 (Completely Satisfied) [@tiliouine2006].


#### NZ-Born

We asked participants "Which country were you born in?".


#### NZ Deprivation Index

We used the NZ Deprivation Index to assign each participant a score based on where they live [@atkinson2019]. This score combines data such as income, home ownership, employment, qualifications, family structure, housing, and access to transport and communication for an area into one deprivation score.



#### NZSEI Occupational Prestige and Status

We assessed occupational prestige and status using the New Zealand Socio-economic Index 13 (NZSEI-13) [@fahy2017a]. This index uses the income, age, and education of a reference group, in this case the 2013 New Zealand census, to calculate an score for each occupational group. Scores range from 10 (Lowest) to 90 (Highest). This list of index scores for occupational groups was used to assign each participant a NZSEI-13 score based on their occupation.


#### Parent

"If you are a parent, what is the birth date of your eldest child?".

#### Partner: Has

"What is your relationship status?" (e.g., single, married, de-facto, civil union, widowed, living together, etc.)


#### Partner: Living with

Participants were asekd "Do you live with your partner?" (1 = Yes, 0 = No).


#### Perceived discrimination - ethnicity
- Feel that I am often discriminated against because of my ethnicity.
- I feel that I am often discriminated against because of my ethnicity.


#### Perceived discrimination - gender

- Feel that I am often discriminated against because of my gender.
- I feel that I am often discriminated against because of my gender.


#### Perceived discrimination - religion

"I feel that I am often discriminated against because of my religious/spiritual beliefs." (1 = Strongly Disagree to 7 = Strongly Agree). (Developed for the NZAVS, Time 7 - time 14)


#### Perceived discrimination - age

- I feel that I am often discriminated against because of my age.


#### Perceived discrimination - ethnic group


- Do you think people from your ethnic group are discriminated against in NZ?
- People from my ethnic group are discriminated against in New Zealand.



#### Perfectionism (1 = Strongly Disagree to 7 = Strongly Agree)

We assessed participants' perfectionism using three items from @rice_short_2014.

(1) Doing my best never seems to be enough; 
(2) My performance rarely measures up to my standards; 
(3) I am hardly ever satisfied with my performance. Participants indicated the extent to which they agree with these items 


#### Permeability of the Self (1 = Strongly Disagree to 7 = Strongly Agree)

"I believe I am capable, as an individual, of improving my status in society."

From @tausch2015does.

#### Political Orientation

We measured participants' political orientation using a single item adapted from @jost_end_2006-1. Participants were asked to rate how politically left-wing versus right-wing they see themselves as being (1 = Extremely Left-wing to 7 = Extremely Right-wing)

#### Power Dependence (1 = Strongly Disagree to 7 = Strongly Agree).

Participants' Power dependence was measured using two items: 

(1) I do not have enough power or control over important parts of my life; 
(2) Other people have too much power or control over important parts of my life. 

From @overall2016power.

#### Religion: Belief in God

Using one item from Eurobarometer (2005), we asked participants "Do you believe in a God" (1 = Yes, 0 = No) [@eurobarometer2005b].

#### Religion: Belief in a Spirit or Life Force

Using one item from Eurobarometer (2005), we asked participants "Do you believe in some form of spirit or lifeforce? (1 = Yes, 0 = No) [@eurobarometer2005b].

#### Religion: Religious Affiliation

Participants were asked to indicate their religion identification ("Do you identify with a religion and/or spiritual group?") on a binary response (1 = Yes, 0 = No). We then asked "What religion or spiritual group?" These questions are used in the New Zealand Census.

#### Religion: Frequency of Religious Service Attendence

If participants answered *yes* to "Do you identify with a religion and/or spiritual group?" we measured their frequency of church attendence using one item from @sibley2012: "how many times did you attend a church or place of worship in the last month?". Those participants who were not religious were imputed a score of "0".

####  Religion: Frequency of Prayer

If participants answered *yes* to "Do you identify with a religion and/or spiritual group?" we measured their frequency of prayer by asking "how many times did you pray in the last week?" Those participants who were not religious were imputed a score of "0" [@Bulbulia_2015].

####  Religion: Frequency of Scripture Reading

If participants answered *yes* to "Do you identify with a religion and/or spiritual group?" we measured their frequency of scripture reading by asking "how many times did you read religious scripture in the last week?" Those participants who were not religious were imputed a score of "0" [@bulbulia2016]

####  Religion: Religious Identification

If participants answered *yes* to "Do you identify with a religion and/or spiritual group? we asked"How important is your religion to how you see yourself?" (1 = Not important, 7 = Very important). Those participants who were not religious were imputed a score of "0".

#### Religion: Spiritual Identification

Spiritual identification was measured using one item ("I identify as a spiritual person.") from @postmes_single-item_2013. Participants indicated their agreement with this item (1 = Strongly Disagree to 7 = Strongly Agree).


#### Retired

Participants were asked to indicate whether they were retiered or not in the last year (1 = Yes, 0 = No).

#### Rumination (ordinal)


* "During the last 30 days, how often did...you have negative thoughts that repeated over and over?" and indicated their frequency of rumination on an ordinal scale 

From @nolen-hoeksema_effects_1993 

Ordinal responses: 0 = None of The Time, 1 = A little of The Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time.



#### Sample Opt-in

The New Zealand Attitudes and Values Study allows opt-ins to the study. Because the opt-in population may differ from those sampled randomly from the New Zealand electoral roll; although the opt-in rate is low, we include an indicator (yes/no) for this variable.



#### Sample Origin

Wave enrolled in NZAVS, see @sibley2021.


#### Self-Esteem (1 = Very inaccurate to 7 = Very accurate)

Participants were instructed to circle the number that best represents how accurately each statement describes them. Participants responded to the items 

1. "On the whole am satisfied with myself;"
2. "Take a positive attitude toward myself;" 
3. "Am inclined to feel that I am a failure." 

Adapted from @Rosenberg1965.

#### Self Control (has) & Self Control (wish had more) (1 = Strongly Disagree to 7 = Strongly Agree).

Participants were asked to indicate the extent to which they endorse the two items:

1. "In general, I have a lot of self-control"
2. "I wish I had more self-discipline" from @tangney_high_2004. 

We assessed these dimensions separatedly



#### Self-Respect (1 = Strongly Disagree to 7 = Strongly Agree)

We assessed participants' levels of self-respect using an item adapted from @tyler_understanding_1996. Participant indicated the extent to which they agree with the statement ("If they knew me, most NZers would respect what I have accomplished in life") on a likert scale (1 = Strongly Disagree to 7 = Strongly Agree)


#### Sense of Belonging (1 = Very Inaccurate to 7  = Very Accurate)

(1) "Know that people in my life accept and value me"; 
(2) "Feel like an outsider" (reversed); 
(3) "Know that people around me share my attitudes and beliefs". 

Adapted from the Sense of Belonging Instrument [@hagerty1995]


#### Social Support (1 = Strongly Disagree to 7 = Strongly Agree)

(1) "There are people I can depend on to help me if I really need
it;" 
(2) "There is no one I can turn to for guidance in times of stress;"  (reversed)
(3) "I know there are people I can turn to when I need help." 


From @cutrona1987 and @williams2000cyberostracism 

#### Semiretired

SAME AS RETIRED

#### Sexual Orientation

Participants were asked to report their sexual orientation: "How would you describe your sexual orientation? (e.g., heterosexual, homosexual, straight, gay, lesbian, bisexual, etc.)".

#### Sexual Satisfaction (1 = Not satisfied to 7 = Very satisfied).

"How satisfied are you with your sex life?" (developed for the NZAVS).

#### Siblings (time 8, time 10)

Participants were asked the following questions related to sibling counts: 
 
 - Were you the 1st born, 2nd born, or 3rd born, etc, child of your mother?
 - Do you have siblings?
 - How many older sisters do you have?
 - How many younger sisters do you have?
 - How many older brothers do you have?
 - How many younger brothers do you have?

A single score was obtained from sibling counts by summing responses to the "How many..." items. From these scores an ordered factor was created ranging from 0 to 7, where participants with more than 7 siblings were grouped into the highest category. 

#### Smoker

We asked participants whether they are currently smoking or not (1 = Yes or 0 = No), using a single item ("Do you currently smoke?) from @muriwai_looking_2018.

#### Socialising (time 10, time 11)

As part of the time usage measures, participants were asked to state how many hour the spent in activities related to socialising with the following groups:

  - Hours spent … socialising with family
  - Hours spent … socialising with friends
  - Hours spent … socialising with community groups
  - Hours spent … socialising with religious groups

#### Standard Living

We measured participants' satisfaction with their standard of living using an item from the Australian Unity Wellbeing Index [@cummins_developing_2003]. Participants read an instruction ("Please rate your level of satisfaction with the following aspects of your life and New Zealand.") and responded to an item ("Your standard of living") on a 10-point scale (0 = completely dissatisfied to 10 = completely satisfied).

#### Support

Participants' perceived social support was measured using three items from @cutrona1987 and @williams_cyberostracism_2000: (1) "There are people I can depend on to help me if I really need it"; (2) "There is no one I can turn to for guidance in times of stress"; (3) "I know there are people I can turn to when I need help." Participants indicated the extent to which they agree with those items (1 = Strongly Disagree to 7 = Strongly Agree). The second item was negatively-worded, so we reversely recorded the responses to this item.


#### Support received: money (waves 10-12) (Study 4 outcomes)

The NZAVS has a 'revealed' measure of received help and support measured in hours of support in the previous week. The items are: 


*Please estimate how much help you have received from the following sources in the last week?*

- *family...MONEY (hours)*
- *friends...MONEY (hours)*
- *members of my community...MONEY (hours)*


Because this measure is highly variable, we convert responses to binary indicators: *0 = none/ 1=any*


#### Support received: time (waves 10-13) (Study 3 outcomes)

*Please estimate how much help you have received from the following sources in the last week?*

- *family...TIME (hours)*
- *friends...TIME (hours)*
- *members of my community.. TIME (hours)*

#### Urban Living Area

We coded whether they are living in an urban or rural area (1 = Urban, 0 = Rural) based on the addresses provided.



#### Subjective Wellbeing

We measured participants' subjective wellbeing using three items from the Australian Unity Wellbeing Index [@cummins_developing_2003]: (1) your health; (2) your future security; (3) your future security. Participants read an instruction ("The following items assess your current satisfaction with different aspects of your life and aspects of New Zealand more generally") and indicated their satisfaction with those items (0 = Completely Dissatisfied to 10 = Completely Satisfied).



Alternative

#### Personal Well-being Relationships  (0 = completely dissatisfied to 10 = completely satisfied)

Participants read an instruction ("Please rate your level of satisfaction with the following aspects of your life and New Zealand.") and responded to an item: 

* "Your relationships"

From the Australian Unity Wellbeing Index [@cummins_developing_2003]


#### Personal Well-being Security  (0 = completely dissatisfied to 10 = completely satisfied)

Participants read an instruction ("Please rate your level of satisfaction with the following aspects of your life and New Zealand.") and responded to an item: 

* "Your future security" 

From the Australian Unity Wellbeing Index [@cummins_developing_2003].


#### Personal Well-being Standard Living  (0 = completely dissatisfied to 10 = completely satisfied)

Participants read an instruction ("Please rate your level of satisfaction with the following aspects of your life and New Zealand.") and responded to an item: 


* "Your standard of living" 

From the Australian Unity Wellbeing Index [@cummins_developing_2003].


#### Personal Well-being Your Health   (0 = completely dissatisfied to 10 = completely satisfied)

Participants read an instruction ("Please rate your level of satisfaction with the following aspects of your life and New Zealand.") and responded to an item: 


* "Your Health"

From the Australian Unity Wellbeing Index [@cummins_developing_2003].







#### Feeling Thermometer (Warmth)

Warmth toward groups was rated by a one-item measure using the "feeling thermometer" scale. Participants were asked to rate their feeling of warmth toward the following groups: NZ European, Māori, Asians in general, Pacific Islanders, Elderly people, People with a disability, Overweight people, Immigrants in general, Chinese, Indians, Muslims, and People with mental illness. Ratings were on a 7-point scale from (1 = least warmth toward a group to 7 = most warmth toward a group, with 4 being neutral. This measure is modelled on affect thermometer items in United States National Election Study [@sibley2020].


####  Short-Form Subjective Health Scale (General Health Perception Subscale), from @instrument1992mos, scored ordinal (1-7)

1. "In general, would you say your health is..."
2. "I seem to get sick a little easier than other people." (reversed)
3. "I expect my health to get worse." (reversed)

#### ELSE

Participants health was measured using one item ("Do you have a health condition or disability that limits you, and that has lasted for 6+ months?"; 1 = Yes, 0 = No) adapted from @verbrugge1997.



\pagebreak

#### References

::: {#refs}
:::
